#!/bin/bash

# Get the directory of this script
DIR=`realpath $(dirname $0)`

source $DIR/.env

# Do not start if a process is already running
if [ "$( $DOCKER container inspect -f '{{.State.Running}}' $DKR_CONTAINER_NAME 2>/dev/null)" == "true" ]; then
  echo "Another ForWarn2 docker process is already running!"
  echo "Exiting..."
  exit
fi

$DOCKER run --rm --tty \
  --network=host \
  --name $DKR_CONTAINER_NAME \
  -v $DIR/:$DKR_BUILD_DIR \
  -v $DIR/$FW2_ARCHIVE_DIR_NORMAL:$DKR_BUILD_DIR/$FW2_ARCHIVE_DIR_NORMAL \
  -v $DIR/$FW2_ARCHIVE_DIR_MUTED:$DKR_BUILD_DIR/$FW2_ARCHIVE_DIR_MUTED \
  -v $DIR/$PRECURSORS_DIR:$DKR_BUILD_DIR/$PRECURSORS_DIR \
  -v $DIR/$ALL_YEAR_MAXES_DIR:$DKR_BUILD_DIR/$ALL_YEAR_MAXES_DIR \
  $DKR_IMAGE_TAG $1
