#!/bin/bash

F1=./maxMODIS.2019.std.test.tif
F2=./maxMODIS.2019.std.test.vrt

echo Test -88.6 37.9
echo

echo TIF TEST:
time gdallocationinfo -valonly -wgs84 $F1 -88.6 37.9

echo
#echo VRT TEST:
#time gdallocationinfo -valonly -wgs84 $F2 -88.6 37.9

echo
echo ----------------------------
echo

echo Test -98.3 33.22
echo

echo TIF TEST:
time gdallocationinfo -valonly -wgs84 $F1 -98.3 33.22

echo
#echo VRT TEST:
#time gdallocationinfo -valonly -wgs84 $F2 -98.3 33.22

