#!/bin/bash

source .env

cd ./gdal_docker

docker build \
  -t $DKR_IMAGE_TAG \
  --build-arg DKR_USER=$DKR_USER \
  --build-arg DKR_GROUP=$DKR_GROUP \
  --build-arg DKR_BUILD_DIR=$DKR_BUILD_DIR \
  .


