#!/bin/bash

source .env

docker run --rm -it \
  --network=host \
  -v $PWD:/build \
  -v $PWD/ForWarn2:/build/ForWarn2 \
  -v $PWD/ForWarn2_Sqrt:/build/ForWarn2_Sqrt \
  -v $PWD/precursors:/build/precursors \
  -v $PWD/graph_data:/build/graph_data \
  $DKR_IMAGE_TAG $1
