#!/bin/bash

pctilepath=/media/disk/fullwrapper2

TYPE=std

for YEAR in 2018
do

   let LASTYEAR=$YEAR-1

   #for DOY in 001 009 017 025 033 041 049 057 065 073 081 089 097 105 113 121 129 137 145 153 161 169 177 185 193 201 209 217 225 233 241 249 257 265 273 281 289 297 305 313 321 329 337 345 353 361
   for DOY in 145
   do


########  calculate three percentiles over all prior max baselines ############

# calculate 90th, 50th and 10th median baselines over all prior years
#  for this DOY

#*******************************************************************
# this is code that writes code for gdal_calc for 50th and 90th and 10th percentile of all prior years, over the entire MODIS period until 2028
#  much shorter than case statements!
#*******************************************************************

#for prioryear in 2002/A 2003/B 2004/C 2005/D 2006/E 2007/F 2008/G 2009/H 2010/I 2011/J 2012/K 2013/L 2014/M 2015/N 2016/O 2017/P 2018/Q 2019/R 2020/S 2021/T 2022/U 2023/V 2024/W 2025/X 2026/Y 2027/Z 2028/AA
for prioryear in 2003/A 2004/B 2005/C 2006/D 2007/E 2008/F 2009/G 2010/H 2011/I 2012/J 2013/K 2014/L 2015/M 2016/N 2017/O 2018/P 2019/Q 2020/R 2021/S 2022/T 2023/U 2024/V 2025/W 2026/X 2027/Y 2028/Z
do

   yr=`echo $prioryear|awk -F/ '{print $1}'`
   ltr=`echo $prioryear|awk -F/ '{print $2}'`

   yrstring=$yrstring" "$yr
   ltrstring=$ltrstring" "$ltr

   if [ $yr -eq $LASTYEAR ]; then
     break
   fi

done

#*******************************************************************


         if [ ! -f $pctilepath/medianallpriormax.$YEAR.$DOY.$TYPE.img ]
         then
            echo "File does not exist for $pctilepath/medianallpriormax."$YEAR"."$DOY"."$TYPE".img"

first=`
echo -n "percentile(["
for cac in $ltrstring
do
   if [ $cac == A ]; then
      echo -n "("$cac"<251)*"$cac
   else
      echo -n ",("$cac"<251)*"$cac
   fi
done

echo -en "],50,axis=0)+("
for cac in $ltrstring
do
   if [ $cac == A ]; then
      echo -n "("$cac"==254)"
   else
      echo -n "&("$cac"==254)"
   fi
done

echo -e ")*0+( ("
for cac in $ltrstring
do
   if [ $cac == A ]; then
      echo -n "("$cac"!=254)"
   else
      echo -n "|("$cac"!=254)"
   fi
done

echo -n ")&("
for cac in $ltrstring
do
   if [ $cac == A ]; then
      echo -n "("$cac">250)"
   else
      echo -n "&("$cac">250)"
   fi
done

echo -n ") )*255"
`

second=`
yr=2003
for cac in $ltrstring
do
   #echo -n " -"$cac" maxMODISmax."$yr".$DOY.$TYPE.img "
   echo -n " -"$cac" "$pctilepath"/maxMODISmax."$yr".$DOY.$TYPE.img "
   let yr=yr+1
done
`

#echo $first
#echo $second

gdal_calc.py --calc="`echo $first`" `echo $second` --outfile=$pctilepath/medianallpriormax.$YEAR.$DOY.$TYPE.img --type=Byte --NoDataValue=252 --format=HFA --co "STATISTICS=YES" --co "COMPRESSED=YES" --overwrite


#gdal_translate $pctilepath/medianallpriormax.$YEAR.$DOY.$TYPE.img -of GTiff $pctilepath/medianallpriormax.$YEAR.$DOY.$TYPE.tif
#rm *.xml
#gdalinfo -stats -hist $pctilepath/medianallpriormax.$YEAR.$DOY.$TYPE.img
#xv $pctilepath/medianallpriormax.$YEAR.$DOY.$TYPE.tif

         else
            echo "medianallpriormax."$YEAR"."$DOY"."$TYPE".img file already exists"
         fi

#*******************************************************************
#*******************************************************************

         if [ ! -f $pctilepath/90thallpriormax.$YEAR.$DOY.$TYPE.img ]
         then
            echo "File does not exist for $pctilepath/90thallpriormax."$YEAR"."$DOY"."$TYPE".img"


first=`
echo -n "percentile(["
for cac in $ltrstring
do
   if [ $cac == A ]; then
      echo -n "("$cac"<251)*"$cac
   else
      echo -n ",("$cac"<251)*"$cac
   fi
done

echo -en "],90,axis=0)+("
for cac in $ltrstring
do
   if [ $cac == A ]; then
      echo -n "("$cac"==254)"
   else
      echo -n "&("$cac"==254)"
   fi
done

echo -e ")*0+( ("
for cac in $ltrstring
do
   if [ $cac == A ]; then
      echo -n "("$cac"!=254)"
   else
      echo -n "|("$cac"!=254)"
   fi
done

echo -n ")&("
for cac in $ltrstring
do
   if [ $cac == A ]; then
      echo -n "("$cac">250)"
   else
      echo -n "&("$cac">250)"
   fi
done

echo -n ") )*255"
`

second=`
yr=2003
for cac in $ltrstring
do
   #echo -n " -"$cac" maxMODISmax."$yr".$DOY.$TYPE.img "
   echo -n " -"$cac" "$pctilepath"/maxMODISmax."$yr".$DOY.$TYPE.img "
   let yr=yr+1
done
`

#echo $first
#echo $second

gdal_calc.py --calc="`echo $first`" `echo $second` --outfile=$pctilepath/90thallpriormax.$YEAR.$DOY.$TYPE.img --type=Byte --NoDataValue=252 --format=HFA --co "STATISTICS=YES" --co "COMPRESSED=YES" --overwrite

#gdal_translate $pctilepath/90thallpriormax.$YEAR.$DOY.$TYPE.img -of GTiff $pctilepath/90thallpriormax.$YEAR.$DOY.$TYPE.tif
#rm *.xml
#gdalinfo -stats -hist $pctilepath/90thallpriormax.$YEAR.$DOY.$TYPE.img
#xv $pctilepath/90thallpriormax.$YEAR.$DOY.$TYPE.tif

         else
            echo "$pctilepath/90thallpriormax."$YEAR"."$DOY"."$TYPE".img file already exists"
         fi

#*******************************************************************
#*******************************************************************
#*******************************************************************

         if [ ! -f $pctilepath/10thallpriormax.$YEAR.$DOY.$TYPE.img ]
         then
            echo "File does not exist for $pctilepath/10thallpriormax."$YEAR"."$DOY"."$TYPE".img"


first=`
echo -n "percentile(["
for cac in $ltrstring
do
   if [ $cac == A ]; then
      echo -n "("$cac"<251)*"$cac
   else
      echo -n ",("$cac"<251)*"$cac
   fi
done

echo -en "],10,axis=0)+("
for cac in $ltrstring
do
   if [ $cac == A ]; then
      echo -n "("$cac"==254)"
   else
      echo -n "&("$cac"==254)"
   fi
done

echo -e ")*0+( ("
for cac in $ltrstring
do
   if [ $cac == A ]; then
      echo -n "("$cac"!=254)"
   else
      echo -n "|("$cac"!=254)"
   fi
done

echo -n ")&("
for cac in $ltrstring
do
   if [ $cac == A ]; then
      echo -n "("$cac">250)"
   else
      echo -n "&("$cac">250)"
   fi
done

echo -n ") )*255"
`

second=`
yr=2003
for cac in $ltrstring
do
   #echo -n " -"$cac" maxMODISmax."$yr".$DOY.$TYPE.img "
   echo -n " -"$cac" "$pctilepath"/maxMODISmax."$yr".$DOY.$TYPE.img "
   let yr=yr+1
done
`

#echo $first
#echo $second

gdal_calc.py --calc="`echo $first`" `echo $second` --outfile=$pctilepath/10thallpriormax.$YEAR.$DOY.$TYPE.img --type=Byte --NoDataValue=252 --format=HFA --co "STATISTICS=YES" --co "COMPRESSED=YES" --overwrite

#gdal_translate $pctilepath/10thallpriormax.$YEAR.$DOY.$TYPE.img -of GTiff $pctilepath/10thallpriormax.$YEAR.$DOY.$TYPE.tif
#rm *.xml
#gdalinfo -stats -hist $pctilepath/10thallpriormax.$YEAR.$DOY.$TYPE.img
#xv $pctilepath/10thallpriormax.$YEAR.$DOY.$TYPE.tif

         else
            echo "$pctilepath/10thallpriormax."$YEAR"."$DOY"."$TYPE".img file already exists"
         fi

#*******************************************************************
#*******************************************************************
##### this is an example of the gdal_calc.py code that this code writes ###
#*******************************************************************
# calculate mean, max, 90th and 50th median baselines over all prior years
#  for this DOY
#case $numyrsprior in
   #16)		# 2019 thru P
#   
#gdal_calc.py --calc="\
#percentile([\
#(A<251)*A,(B<251)*B,(C<251)*C,\
#(D<251)*D,(E<251)*E,(F<251)*F,\
#(G<251)*G,(H<251)*H,(I<251)*I,\
#(J<251)*J,(K<251)*K,(L<251)*L,\
#(M<251)*M,(N<251)*N,(O<251)*O,\
#(P<251)*P\
#],50,axis=0)\
#+(\
#(A==254)&(B==254)&(C==254)&\
#(D==254)&(E==254)&(F==254)&\
#(G==254)&(H==254)&(I==254)&\
#(J==254)&(K==254)&(L==254)&\
#(M==254)&(N==254)&(O==254)&\
#(P==254)\
#)*0\
#+( (\
#(A!=254)|(B!=254)|(C!=254)|\
#(D!=254)|(E!=254)|(F!=254)|\
#(G!=254)|(H!=254)|(I!=254)|\
#(J!=254)|(K!=254)|(L!=254)|\
#(M!=254)|(N!=254)|(O!=254)|\
#(P!=254)\
 #)&\
#( \
#(A>250)&(B>250)&(C>250)&\
#(D>250)&(E>250)&(F>250)&\
#(G>250)&(H>250)&(I>250)&\
#(J>250)&(K>250)&(L>250)&\
#(M>250)&(N>250)&(O>250)&\
#(P>250)\
 #) )*255\
#" \
#-A maxMODISmax.2003.$DOY.$TYPE.img -B maxMODISmax.2004.$DOY.$TYPE.img \
#-C maxMODISmax.2005.$DOY.$TYPE.img -D maxMODISmax.2006.$DOY.$TYPE.img \
#-E maxMODISmax.2007.$DOY.$TYPE.img -F maxMODISmax.2008.$DOY.$TYPE.img \
#-G maxMODISmax.2009.$DOY.$TYPE.img -H maxMODISmax.2010.$DOY.$TYPE.img \
#-I maxMODISmax.2011.$DOY.$TYPE.img -J maxMODISmax.2012.$DOY.$TYPE.img \
#-K maxMODISmax.2013.$DOY.$TYPE.img -L maxMODISmax.2014.$DOY.$TYPE.img \
#-M maxMODISmax.2015.$DOY.$TYPE.img -N maxMODISmax.2016.$DOY.$TYPE.img \
#-O maxMODISmax.2017.$DOY.$TYPE.img -P maxMODISmax.2018.$DOY.$TYPE.img \
#--outfile=medianallpriormax.$YEAR.$DOY.$TYPE.img --type=Byte --NoDataValue=252 --format=HFA --co "STATISTICS=YES" --co "COMPRESSED=YES" --overwrite
#
#gdal_translate medianallpriormax.$YEAR.$DOY.$TYPE.img -of GTiff medianallpriormax.$YEAR.$DOY.$TYPE.tif
#rm *.xml
#gdalinfo -stats -hist medianallpriormax.$YEAR.$DOY.$TYPE.img
#xv medianallpriormax.$YEAR.$DOY.$TYPE.tif
#
#
#gdal_calc.py --calc="\
#percentile([\
#(A<251)*A,(B<251)*B,(C<251)*C,\
#(D<251)*D,(E<251)*E,(F<251)*F,\
#(G<251)*G,(H<251)*H,(I<251)*I,\
#(J<251)*J,(K<251)*K,(L<251)*L,\
#(M<251)*M,(N<251)*N,(O<251)*O,\
#(P<251)*P\
#],90,axis=0)\
#+(\
#(A==254)&(B==254)&(C==254)&\
#(D==254)&(E==254)&(F==254)&\
#(G==254)&(H==254)&(I==254)&\
#(J==254)&(K==254)&(L==254)&\
#(M==254)&(N==254)&(O==254)&\
#(P==254)\
#)*0\
#+( (\
#(A!=254)|(B!=254)|(C!=254)|\
#(D!=254)|(E!=254)|(F!=254)|\
#(G!=254)|(H!=254)|(I!=254)|\
#(J!=254)|(K!=254)|(L!=254)|\
#(M!=254)|(N!=254)|(O!=254)|\
#(P!=254)\
 #)&\
#( \
#(A>250)&(B>250)&(C>250)&\
#(D>250)&(E>250)&(F>250)&\
#(G>250)&(H>250)&(I>250)&\
#(J>250)&(K>250)&(L>250)&\
#(M>250)&(N>250)&(O>250)&\
#(P>250)\
 #) )*255\
#" \
#-A maxMODISmax.2003.$DOY.$TYPE.img -B maxMODISmax.2004.$DOY.$TYPE.img \
#-C maxMODISmax.2005.$DOY.$TYPE.img -D maxMODISmax.2006.$DOY.$TYPE.img \
#-E maxMODISmax.2007.$DOY.$TYPE.img -F maxMODISmax.2008.$DOY.$TYPE.img \
#-G maxMODISmax.2009.$DOY.$TYPE.img -H maxMODISmax.2010.$DOY.$TYPE.img \
#-I maxMODISmax.2011.$DOY.$TYPE.img -J maxMODISmax.2012.$DOY.$TYPE.img \
#-K maxMODISmax.2013.$DOY.$TYPE.img -L maxMODISmax.2014.$DOY.$TYPE.img \
#-M maxMODISmax.2015.$DOY.$TYPE.img -N maxMODISmax.2016.$DOY.$TYPE.img \
#-O maxMODISmax.2017.$DOY.$TYPE.img -P maxMODISmax.2018.$DOY.$TYPE.img\
#--outfile=90thallpriormax.$YEAR.$DOY.$TYPE.img --type=Byte --NoDataValue=252 --format=HFA --co "STATISTICS=YES" --co "COMPRESSED=YES" --overwrite
#
#gdal_translate 90thallpriormax.$YEAR.$DOY.$TYPE.img -of GTiff 90thallpriormax.$YEAR.$DOY.$TYPE.tif
#rm *.xml
#gdalinfo -stats -hist 90thallpriormax.$YEAR.$DOY.$TYPE.img
#xv 90thallpriormax.$YEAR.$DOY.$TYPE.tif
#
#
#gdal_calc.py --calc="\
#maximum.reduce([\
#(A<251)*A,(B<251)*B,(C<251)*C,\
#(D<251)*D,(E<251)*E,(F<251)*F,\
#(G<251)*G,(H<251)*H,(I<251)*I,\
#(J<251)*J,(K<251)*K,(L<251)*L,\
#(M<251)*M,(N<251)*N,(O<251)*O,\
#(P<251)*P\
#],axis=0)\
#+(\
#(A==254)&(B==254)&(C==254)&\
#(D==254)&(E==254)&(F==254)&\
#(G==254)&(H==254)&(I==254)&\
#(J==254)&(K==254)&(L==254)&\
#(M==254)&(N==254)&(O==254)&\
#(P==254)\
#)*0\
#+( (\
#(A!=254)|(B!=254)|(C!=254)|\
#(D!=254)|(E!=254)|(F!=254)|\
#(G!=254)|(H!=254)|(I!=254)|\
#(J!=254)|(K!=254)|(L!=254)|\
#(M!=254)|(N!=254)|(O!=254)|\
#(P!=254)\
# )&\
#( \
#(A>250)&(B>250)&(C>250)&\
#(D>250)&(E>250)&(F>250)&\
#(G>250)&(H>250)&(I>250)&\
#(J>250)&(K>250)&(L>250)&\
#(M>250)&(N>250)&(O>250)&\
#(P>250)\
# ) )*255\
#" \
#-A maxMODISmax.2003.$DOY.$TYPE.img -B maxMODISmax.2004.$DOY.$TYPE.img \
#-C maxMODISmax.2005.$DOY.$TYPE.img -D maxMODISmax.2006.$DOY.$TYPE.img \
#-E maxMODISmax.2007.$DOY.$TYPE.img -F maxMODISmax.2008.$DOY.$TYPE.img \
#-G maxMODISmax.2009.$DOY.$TYPE.img -H maxMODISmax.2010.$DOY.$TYPE.img \
#-I maxMODISmax.2011.$DOY.$TYPE.img -J maxMODISmax.2012.$DOY.$TYPE.img \
#-K maxMODISmax.2013.$DOY.$TYPE.img -L maxMODISmax.2014.$DOY.$TYPE.img \
#-M maxMODISmax.2015.$DOY.$TYPE.img -N maxMODISmax.2016.$DOY.$TYPE.img \
#-O maxMODISmax.2017.$DOY.$TYPE.img -P maxMODISmax.2018.$DOY.$TYPE.img\
#--outfile=maxallpriormax.$YEAR.$DOY.$TYPE.img --type=Byte --NoDataValue=252 --format=HFA --co "STATISTICS=YES" --co "COMPRESSED=YES" --overwrite
#
##gdal_translate maxallpriormax.$YEAR.$DOY.$TYPE.img -of GTiff maxallpriormax.$YEAR.$DOY.$TYPE.tif
##rm *.xml
##gdalinfo -stats -hist maxallpriormax.$YEAR.$DOY.$TYPE.img
##xv maxallpriormax.$YEAR.$DOY.$TYPE.tif
#
#
#gdal_calc.py --calc="\
#mean([\
#(A<251)*A,(B<251)*B,(C<251)*C,\
#(D<251)*D,(E<251)*E,(F<251)*F,\
#(G<251)*G,(H<251)*H,(I<251)*I,\
#(J<251)*J,(K<251)*K,(L<251)*L,\
#(M<251)*M,(N<251)*N,(O<251)*O,\
#(P<251)*P\
#],axis=0)\
#+(\
#(A==254)&(B==254)&(C==254)&\
#(D==254)&(E==254)&(F==254)&\
#(G==254)&(H==254)&(I==254)&\
#(J==254)&(K==254)&(L==254)&\
#(M==254)&(N==254)&(O==254)&\
#(P==254)\
#)*0\
#+( (\
#(A!=254)|(B!=254)|(C!=254)|\
#(D!=254)|(E!=254)|(F!=254)|\
#(G!=254)|(H!=254)|(I!=254)|\
#(J!=254)|(K!=254)|(L!=254)|\
#(M!=254)|(N!=254)|(O!=254)\
#(P!=254)\
# )&\
#( \
#(A>250)&(B>250)&(C>250)&\
#(D>250)&(E>250)&(F>250)&\
#(G>250)&(H>250)&(I>250)&\
#(J>250)&(K>250)&(L>250)&\
#(M>250)&(N>250)&(O>250)&\
#(P>250)\
# ) )*255\
#" \
#-A maxMODISmax.2003.$DOY.$TYPE.img -B maxMODISmax.2004.$DOY.$TYPE.img \
#-C maxMODISmax.2005.$DOY.$TYPE.img -D maxMODISmax.2006.$DOY.$TYPE.img \
#-E maxMODISmax.2007.$DOY.$TYPE.img -F maxMODISmax.2008.$DOY.$TYPE.img \
#-G maxMODISmax.2009.$DOY.$TYPE.img -H maxMODISmax.2010.$DOY.$TYPE.img \
#-I maxMODISmax.2011.$DOY.$TYPE.img -J maxMODISmax.2012.$DOY.$TYPE.img \
#-K maxMODISmax.2013.$DOY.$TYPE.img -L maxMODISmax.2014.$DOY.$TYPE.img \
#-M maxMODISmax.2015.$DOY.$TYPE.img -N maxMODISmax.2016.$DOY.$TYPE.img \
#-O maxMODISmax.2017.$DOY.$TYPE.img -P maxMODISmax.2018.$DOY.$TYPE.img\
#--outfile=meanallpriormax.$YEAR.$DOY.$TYPE.img --type=Byte --NoDataValue=252 --format=HFA --co "STATISTICS=YES" --co "COMPRESSED=YES" --overwrite
#
#gdal_translate meanallpriormax.$YEAR.$DOY.$TYPE.img -of GTiff meanallpriormax.$YEAR.$DOY.$TYPE.tif
#rm *.xml
#gdalinfo -stats -hist meanallpriormax.$YEAR.$DOY.$TYPE.img
#xv meanallpriormax.$YEAR.$DOY.$TYPE.tif
#
#;;




#################################################################

done	# over all intervals

done	# over all years
