#!/bin/bash

DATASET=$1

gdal_calc.py -A Terra.img -B Aqua.img --outfile=maxMODIS.$YEAR.$DOY.std.img --calc="\
maximum((A<251)*A,(B<251)*B)\
+(((A==253)&(B==253))|((A==253)&(B==255))|((A==255)&(B==253))|((A==255)&(B==255)))*255\
+((A==254)|(B==254))*254\
" --format=HFA --co "STATISTICS=YES" --co "COMPRESSED=YES" --NoDataValue=252 --type=Byte --overwrite


